### PR TITLE
new feature version info in column Last Build

### PR DESCRIPTION
**Pull request by juergens73**
First of all you provide a really great extension that I use for years in my Jenkins CI projects.
I need an extension in column "Last Build". Therefore, I implemented build version information in column "Last Build".

Please could you merge/integrate the branch "feature/last-vesion" from my fork https://github.com/juergens73/extra-columns-plugin . I would be really glad if you could merge the extension in the next release.

**Change of implementation**

- I added a boolean option "showVersion" in column config "Last Build". 
- The version is extracted from the build description.
- The header changed to "Last XXX Version", if showVersion is marked, otherwise the current header "Last XXX Build" is displayed. 
- Please, read the details in README.md

Do not hesitate to contact me if you have any questions or if I can support you.

Kind Regards from Munich/Germany
Juergen

----

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by fredg02** [comment]
Thanks for your pull request. I will try to take a closer look at it in the next days.

**Comment by fredg02** [comment]
AFAICT this is a very specific use case. Can you elaborate how you are using the version info in combination with the last build column? (if possible with a screenshot)

**Comment by juergens73** [comment]
Thank you for reviewing my changes. I created some screenshots into a PDF file. You can load from here.
[https://events.schranz.club/shared/extra-columns-plugin-last-build-version.pdf](https://events.schranz.club/shared/extra-columns-plugin-last-build-version.pdf)

The version information of the last success and last failed builds are important to. It is a great advantage to get the build time as well the version or commit that used for the build.

**Comment by fredg02** [comment]
Sorry for the late reply. Thanks for the PDF that explains your use case. I still think your patch solves a very specific use-case. It might be better to include it in a separate plugin. Without more demand for this feature, I currently don't have enough time to integrate and support it.

**Pull request closed without merging**
