### PR TITLE
Change LastBuildConsoleColumn to use console#footer

### PR DESCRIPTION
**Pull request by peinheber-mersive**

### CODE REVIEW

**Comment by peinheber-mersive** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-61186

**Comment by ljader** [comment]
Makes sense 👍

**Comment by fredg02** [comment]
I agree with jumping to console#footer by default, but loading the full console by default might cause delays when the console log is huge (unfortunately, logs with several 100MBs are real).
Showing the full console should be optional and off by default.

**Comment by ljader** [comment]
Maybe is should be configurable like I did in other project:
https://github.com/jenkinsci/buildtriggerbadge-plugin/commit/94eda6518004133f0f11af0c38ee14d1ad593669

**Comment by peinheber-mersive** [comment]
Configurable would be nice, but I'm afraid I don't have time to make that big of a change.  For my use, consoleFull would be preferable, but I understand the large log issue.  I've updated to just use #footer.

**Comment by fredg02** [comment]
LGTM. Thanks for the pull request!

**Pull request merged**
